### ISSUE TITLE
[FIX] like/dislike API 수정

### ISSUE THREAD

**Issue by sangkim99** [likelion-hackton/backend#73]
* like/dislike 버튼 눌렀는지 안눌렀는지 프런트에서 확인 불가능
* api 한개로 합치기

**Comment by emadellaloggia** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
